Update user profile
debabin/shift-backend pull request #1
Opened 2024-01-22 15:14 UTC by anv296

2024-01-22 15:50 UTC, debabin requested changes

2024-01-22 15:50 UTC, debabin commented on src/modules/cinema/cinema.controller.ts
> +    );
А что если пользователя нет ?

2024-01-22 15:50 UTC, debabin commented on src/schema.gql
> +  session: SessionResponse!
А почему поменялось на session ?

2024-01-24 14:07 UTC, anv296 commented on src/modules/cinema/cinema.controller.ts
> +    );
сделал аналогично как в других местах

2024-01-24 14:07 UTC, anv296 commented on src/schema.gql
> +  session: SessionResponse!
а почему было me? сделал аналогично остальным

2024-01-28 04:58 UTC, merged